version: '3'

services:
  ingress:
      container_name: ingress
      build: ./ingress
      image: ingress:latest
      volumes:
        - ./ingress/nginx.conf:/etc/nginx/nginx.conf
        - ./ingress/conf.d:/etc/nginx/conf.d
        - /var/log/nginx:/var/log/nginx
      ports:
        - "8500:80"
      hostname: ingress
      restart: unless-stopped

  green-backend:
      container_name: green-backend
      build: ./backend
      volumes:
        - /var/log/green-backend:/var/log
      hostname: green-backend
      restart: unless-stopped

  blue-backend:
      container_name: blue-backend
      build: ./backend
      volumes:
        - /var/log/blue-backend:/var/log
      hostname: blue-backend
      restart: unless-stopped
